// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/myacey/jxgercorp-banking/services/user/internal/models/entity"
)

type UserStatusEnum string

const (
	UserStatusEnumPending UserStatusEnum = "pending"
	UserStatusEnumActive  UserStatusEnum = "active"
	UserStatusEnumBanned  UserStatusEnum = "banned"
)

func (e *UserStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatusEnum(s)
	case string:
		*e = UserStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatusEnum: %T", src)
	}
	return nil
}

type NullUserStatusEnum struct {
	UserStatusEnum UserStatusEnum
	Valid          bool // Valid is true if UserStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatusEnum), nil
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	Status         entity.UserStatus
}
