// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	ChangeUserBalance(ctx context.Context, arg ChangeUserBalanceParams) (User, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUserByUsername(ctx context.Context, username string) error
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	SearchIncomeTransactions(ctx context.Context, arg SearchIncomeTransactionsParams) ([]Transaction, error)
	SearchOutcomeTransactions(ctx context.Context, arg SearchOutcomeTransactionsParams) ([]Transaction, error)
	SearchTransactionsWithUser(ctx context.Context, arg SearchTransactionsWithUserParams) ([]Transaction, error)
	UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error)
}

var _ Querier = (*Queries)(nil)
