// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/myacey/jxgercorp-banking/services/transfer/internal/models/entity"
)

const addAccountBalance = `-- name: AddAccountBalance :one
UPDATE accounts
SET balance = balance + $2
WHERE id = $1
RETURNING id, owner_username, balance, currency, created_at
`

type AddAccountBalanceParams struct {
	ID         uuid.UUID
	AddBalance int64
}

func (q *Queries) AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, addAccountBalance, arg.ID, arg.AddBalance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerUsername,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const addTwoAccountsBalance = `-- name: AddTwoAccountsBalance :many
UPDATE accounts
SET balance = CASE
    WHEN id = $2 THEN balance - $1
    WHEN id = $3 THEN balance + $1
END
WHERE id IN ($2, $3)
RETURNING id, owner_username, balance, currency, created_at
`

type AddTwoAccountsBalanceParams struct {
	Balance       int64
	FromAccountID uuid.UUID
	ToAccountID   uuid.UUID
}

func (q *Queries) AddTwoAccountsBalance(ctx context.Context, arg AddTwoAccountsBalanceParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, addTwoAccountsBalance, arg.Balance, arg.FromAccountID, arg.ToAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUsername,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id,
    owner_username,
    balance,
    currency,
    created_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, owner_username, balance, currency, created_at
`

type CreateAccountParams struct {
	ID            uuid.UUID
	OwnerUsername string
	Balance       int64
	Currency      entity.Currency
	CreatedAt     time.Time
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.OwnerUsername,
		arg.Balance,
		arg.Currency,
		arg.CreatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerUsername,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, owner_username, balance, currency, created_at FROM accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerUsername,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const searchAccounts = `-- name: SearchAccounts :many
SELECT id, owner_username, balance, currency, created_at
FROM accounts
WHERE owner_username = $1
  AND ($2::currency_enum IS NULL OR currency = $2::currency_enum)
`

type SearchAccountsParams struct {
	Username string
	Currency NullCurrencyEnum
}

func (q *Queries) SearchAccounts(ctx context.Context, arg SearchAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, searchAccounts, arg.Username, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUsername,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
