// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAccountBalance = `-- name: AddAccountBalance :one
UPDATE accounts
SET balance = balance + $2
WHERE id = $1
RETURNING id, owner_username, balance, created_at, currency_code
`

type AddAccountBalanceParams struct {
	ID         uuid.UUID
	AddBalance int64
}

func (q *Queries) AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, addAccountBalance, arg.ID, arg.AddBalance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerUsername,
		&i.Balance,
		&i.CreatedAt,
		&i.CurrencyCode,
	)
	return i, err
}

const addTwoAccountsBalance = `-- name: AddTwoAccountsBalance :many
UPDATE accounts
SET balance = CASE
    WHEN id = $2 THEN balance - $1
    WHEN id = $3 THEN balance + $1
END
WHERE id IN ($2, $3)
RETURNING id, owner_username, balance, created_at, currency_code
`

type AddTwoAccountsBalanceParams struct {
	Balance       int64
	FromAccountID uuid.UUID
	ToAccountID   uuid.UUID
}

func (q *Queries) AddTwoAccountsBalance(ctx context.Context, arg AddTwoAccountsBalanceParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, addTwoAccountsBalance, arg.Balance, arg.FromAccountID, arg.ToAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUsername,
			&i.Balance,
			&i.CreatedAt,
			&i.CurrencyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id,
    owner_username,
    balance,
    currency_code,
    created_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, owner_username, balance, created_at, currency_code
`

type CreateAccountParams struct {
	ID            uuid.UUID
	OwnerUsername string
	Balance       int64
	CurrencyCode  string
	CreatedAt     time.Time
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.OwnerUsername,
		arg.Balance,
		arg.CurrencyCode,
		arg.CreatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerUsername,
		&i.Balance,
		&i.CreatedAt,
		&i.CurrencyCode,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :one
DELETE FROM accounts
WHERE id  = $1
RETURNING id
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAccount, id)
	err := row.Scan(&id)
	return id, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, owner_username, balance, created_at, currency_code FROM accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerUsername,
		&i.Balance,
		&i.CreatedAt,
		&i.CurrencyCode,
	)
	return i, err
}

const getCurrencies = `-- name: GetCurrencies :many
SELECT code, symbol, precision FROM currencies
`

func (q *Queries) GetCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, getCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(&i.Code, &i.Symbol, &i.Precision); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccounts = `-- name: SearchAccounts :many
SELECT id, owner_username, balance, created_at, currency_code
FROM accounts
WHERE owner_username = $1
  AND ($2::text IS NULL OR currency_code = $2::text)
`

type SearchAccountsParams struct {
	Username     string
	CurrencyCode pgtype.Text
}

func (q *Queries) SearchAccounts(ctx context.Context, arg SearchAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, searchAccounts, arg.Username, arg.CurrencyCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUsername,
			&i.Balance,
			&i.CreatedAt,
			&i.CurrencyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
