// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID            uuid.UUID
	OwnerUsername string
	Balance       int64
	CreatedAt     time.Time
	CurrencyCode  string
}

type Currency struct {
	Code      string
	Symbol    string
	Precision int32
}

type Transfer struct {
	ID                  uuid.UUID
	FromAccountID       uuid.UUID
	ToAccountID         uuid.UUID
	Amount              int64
	CreatedAt           time.Time
	CurrencyCode        string
	FromAccountUsername string
	ToAccountUsername   string
}
