// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/myacey/jxgercorp-banking/services/transfer/internal/models/entity"
)

type CurrencyEnum string

const (
	CurrencyEnumRUB CurrencyEnum = "RUB"
	CurrencyEnumUSD CurrencyEnum = "USD"
	CurrencyEnumEUR CurrencyEnum = "EUR"
)

func (e *CurrencyEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CurrencyEnum(s)
	case string:
		*e = CurrencyEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CurrencyEnum: %T", src)
	}
	return nil
}

type NullCurrencyEnum struct {
	CurrencyEnum CurrencyEnum
	Valid        bool // Valid is true if CurrencyEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrencyEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CurrencyEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CurrencyEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrencyEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CurrencyEnum), nil
}

type Account struct {
	ID            uuid.UUID
	OwnerUsername string
	Balance       int64
	Currency      entity.Currency
	CreatedAt     time.Time
}

type Transfer struct {
	ID            uuid.UUID
	FromAccountID uuid.UUID
	ToAccountID   uuid.UUID
	Amount        int64
	CreatedAt     time.Time
}
