// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	AddTwoAccountsBalance(ctx context.Context, arg AddTwoAccountsBalanceParams) ([]Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	SearchAccounts(ctx context.Context, arg SearchAccountsParams) ([]Account, error)
	SearchTransfersWithAccount(ctx context.Context, arg SearchTransfersWithAccountParams) ([]Transfer, error)
}

var _ Querier = (*Queries)(nil)
