// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transfer.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
    id,
    from_account_id,
    to_account_id,
    amount
) VALUES ($1, $2, $3, $4)
RETURNING id, from_account_id, to_account_id, amount, created_at
`

type CreateTransferParams struct {
	ID            uuid.UUID
	FromAccountID uuid.UUID
	ToAccountID   uuid.UUID
	Amount        int64
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.ID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const searchTransfersWithAccount = `-- name: SearchTransfersWithAccount :many
SELECT id, from_account_id, to_account_id, amount, created_at FROM transfers
WHERE from_account_id = $3 OR to_account_id = $3
ORDER BY created_at DESC
OFFSET $1 LIMIT $2
`

type SearchTransfersWithAccountParams struct {
	Offset        int32
	Limit         int32
	SearchAccount uuid.UUID
}

func (q *Queries) SearchTransfersWithAccount(ctx context.Context, arg SearchTransfersWithAccountParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, searchTransfersWithAccount, arg.Offset, arg.Limit, arg.SearchAccount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
