services:
  postgres:
    image: postgres:17-alpine
    env_file: ".env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - backend-net
    volumes:
      - ./db/data/db:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    env_file: ".env"
    environment:
      - REDIS_PASSWORD=${DB_PASSWORD}
      - REDIS_USER_PASSWORD=${DB_PASSWORD}
      - REDIS_DATABASE=0
    # volumes:
    #   - redis_data:/data
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $DB_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$DB_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    ports:
      - "6379:6379" 
    networks:
      - backend-net
  
  migrate:
      image: migrate/migrate
      networks:
          - backend-net
      volumes:
          - ./db//migration/:/migrations
      entrypoint: ["/bin/sh", "/migrations/migrate-entrypoint.sh"]
      links:
        - postgres
      depends_on:
        - postgres

networks:
  backend-net:
    driver: bridge
