FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache bash git

COPY front/package*.json front/yarn.lock* ./

RUN yarn install

COPY front/ .

COPY front/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
